---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: ubi9
    image: ubi9/ubi-init
    pre_build_image: true
  - name: ubi8
    image: ubi8/ubi-init
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      ubi8:
        atuin_client_libc_variant: "musl"
      ubi9:
        atuin_client_libc_variant: "gnu"
verifier:
  name: ansible
driver:
  name: docker