---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: ubi8
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
    platform: linux/amd64
  - name: ubi9
    image: registry.access.redhat.com/ubi9/ubi-init:latest
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: "/usr/sbin/init"
    platform: linux/amd64
provisioner:
  name: ansible
  inventory:
    host_vars:
      ubi8:
        atuin_client_libc_variant: "musl"
      ubi9:
        atuin_client_libc_variant: "gnu"
verifier:
  name: ansible
