- name: Prepare containers for molecule tests
  hosts: all
  gather_facts: false
  tasks:
    - name: Install tar for during tests
      ansible.builtin.dnf:
        name: tar
        state: present
        use_backend: dnf4
      when: ansible_hostname == "ubi8"

    - name: Install tar for during tests
      ansible.builtin.dnf:
        name: tar
        state: present
        use_backend: dnf5
      when: ansible_hostname == "ubi9"

    - name: Add the user 'johnc'
      ansible.builtin.user:
        name: johnc
        comment: John Connor
