- name: Prepare containers for molecule tests
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Install tar for during tests
      ansible.builtin.package:
        name: tar
        state: present
