- name: Prepare containers for molecule tests
  hosts: all
  gather_facts: false
  tasks:
    - name: Install tar for during tests
      ansible.builtin.package:
        name: tar
        state: present

    - name: Add the user 'johnc'
      ansible.builtin.user:
        name: johnc
        comment: John Connor
