- name: Verify
  hosts: molecule
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false

  tasks:
    - name: Check if atuin binary exists
      block:
        - name: Check for existence for /usr/local/bin/atuin
          ansible.builtin.stat:
            path: /usr/local/bin/atuin
          register: atuin_stat_result

        - name: Verify result of previous task
          ansible.builtin.assert:
            that:
              - atuin_stat_result.stat.exists
