- name: Get user info for {{ item }}
  ansible.builtin.getent:
    database: passwd
    key: "{{ item }}"

- name: Make sure configuration directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.getent_passwd[item][4] }}/.config/atuin"
    owner: "{{ item }}"
    state: directory
    mode: "0750"

- name: Configure atuin client
  ansible.builtin.template:
    dest: "{{ ansible_facts.getent_passwd[item][4] }}/.config/atuin/config.toml"
    src: config.toml.j2
    owner: "{{ item }}"
    mode: "0640"
