- name: Converge server
  hosts: all
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false
  vars:
    atuin_client_version: 18.3.0
    atuin_server_db_uri: "postgres://atuin:atuin@{{ atuin_server_host }}/atuin"

  pre_tasks:
    - name: Gather required subset of facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - default_ipv4

  roles:
    - role: atuin_server
