- name: Verify
  hosts: all
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false
  vars:
    atuin_server_home: /home/atuin

  tasks:
    - name: Check if atuin server config exists
      block:
        - name: Check for existence of server configuration file
          ansible.builtin.stat:
            path: "{{ atuin_server_home }}/.config/atuin/server.toml"
          register: atuin_server_config_stat_result

        - name: Verify result of previous task
          ansible.builtin.assert:
            that:
              - atuin_server_config_stat_result.stat.exists

        - name: Check for existence of systemd unit file
          ansible.builtin.stat:
            path: /etc/systemd/system/atuin.service
          register: atuin_server_unit_stat_result

        - name: Verify result of previous task
          ansible.builtin.assert:
            that:
              - atuin_server_unit_stat_result.stat.exists
