name: Run ansible-lint on code

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v24.2.0
