name: Molecule Tests

on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ${{ github.repository }}/roles/atuin_client
          molecule_args: --scenario-name docker
        env:
          ANSIBLE_FORCE_COLOR: '1'
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ${{ github.repository }}/roles/atuin_server
          molecule_args: --scenario-name default
        env:
          ANSIBLE_FORCE_COLOR: '1'