name: Molecule Tests atuin client

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy_to_galaxy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Ansible Galaxy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          publish: false
          api_key: ${{ secrets.GALAXY_API_KEY }}
