name: Lint, test and tag

on: push

jobs:
  lint-all-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run-ansible-lint
        uses: ansible/ansible-lint@v24.2.0

  molecule-atuin-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Run molecule tests for atuin_client role
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ${{ github.repository }}/roles/atuin_client
          molecule_args: --scenario-name docker --driver-name docker
        env:
          ANSIBLE_FORCE_COLOR: '1'

  molecule-atuin-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Run molecule tests for atuin_server role
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ${{ github.repository }}/roles/atuin_server
          molecule_args: --scenario-name default --driver-name docker
        env:
          ANSIBLE_FORCE_COLOR: '1'

  tag-new-versions:
    runs-on: ubuntu-latest
    needs:
      - molecule-atuin-client
      - molecule-atuin-server
      - lint-all-files
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            awk ' /version: /  { print $2 } ' galaxy.yml | tr -d '"'
